# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Openation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': '用户咨询', 'verbose_name_plural': '用户咨询'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户学习课程', 'verbose_name_plural': '用户学习课程'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户消息接受', 'verbose_name_plural': '用户消息接受'},
        ),
    ]
