# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '学习课程', 'verbose_name_plural': '学习课程'},
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '学习资源', 'verbose_name_plural': '学习资源'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '学习章节', 'verbose_name_plural': '学习章节'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '学习视频', 'verbose_name_plural': '学习视频'},
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源下载'),
        ),
    ]
