# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_auto_20180503_1507'),
        ('Courses', '0002_auto_20180429_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
