# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default=0, max_length=10, verbose_name='关联课程标签'),
        ),
    ]
