# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图地址')),
                ('url', models.URLField(max_length=150, verbose_name='访问地址')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='加入时间')),
                ('index', models.IntegerField(default=100, verbose_name='排序（从小到大）')),
            ],
            options={
                'db_table': 'Banner',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='发送类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'db_table': 'EmailRecord',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
