# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '城市信息', 'verbose_name_plural': '城市信息'},
        ),
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '课程机构', 'verbose_name_plural': '课程机构'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '机构教师', 'verbose_name_plural': '机构教师'},
        ),
    ]
